version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"
    ignore: []
    rebase-strategy: "auto"
    security-updates: true

  - package-ecosystem: "npm"
    directory: "/src/Clients/MCPhappey.Clients.Web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    allow:
      - dependency-type: "all"
    ignore: []
    rebase-strategy: "auto"
    security-updates: true
