# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fakton-mcp-beta

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore src/Samples/MCPhappey.WebApi/MCPhappey.WebApi.csproj

      - name: Build WebAPI project
        run: dotnet build src/Samples/MCPhappey.WebApi/MCPhappey.WebApi.csproj --configuration Release

      - name: Publish WebAPI project
        run: dotnet publish src/Samples/MCPhappey.WebApi/MCPhappey.WebApi.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_681FE200CD3E4555A1AA4B24884F414E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_23EEA0AFAA3E4633AC751EBEEBE19F04 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_88A22C9533D64A6395C2D19A37E9273A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fakton-mcp-beta'
          slot-name: 'Production'
          package: .
          